export const Cursos = [
  {
    categoria: "Pestañas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Extensión Clásica",
    precio: 20000,
    aclaraciones: "",
  },
  {
    categoria: "Cejas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Diseño de Cejas",
    precio: 15000,
    aclaraciones: "",
  },
];

export const Peinados = []

export const Depilacion = [
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion:
      "Promo 1: Pierna + cavado + axila + tira de cola (Bozo de regalo)",
    precio: 11400,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Promo 2: Pierna + cavado + axila",
    precio: 9800,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Promo 3: Cavado + tira de cola",
    precio: 8300,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Promo 4: Rostro completo",
    precio: 4500,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Promo 5: Siete zonas a elección",
    precio: 15500,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Promo 6: Cuerpo completo más de siete zonas a elección",
    precio: 18000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Bozo",
    precio: 2500,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Mentón",
    precio: 2500,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Axila",
    precio: 4000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Abdomen",
    precio: 4500,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Espalda",
    precio: 5000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Brazos",
    precio: 4500,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "1/2 Brazo",
    precio: 3000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Piernas",
    precio: 5000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "1/2 Pierna",
    precio: 3000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Cavado",
    precio: 4000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Tira de cola",
    precio: 3000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Mujeres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Glúteos",
    precio: 4500,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Promo 1: Pecho + abdomen + axila + pierna",
    precio: 12900,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Promo 2: Pecho + abdomen + espalda",
    precio: 11400,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Promo 3: Pecho + abdomen + piernas",
    precio: 9000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Promo 4: Rostro completo",
    precio: 5000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Promo 5: Siete zonas a elección",
    precio: 17000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Promo 6: Más de siete zonas a elección",
    precio: 19500,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Bozo",
    precio: 3000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Mentón",
    precio: 3000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Axila",
    precio: 4500,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Abdomen",
    precio: 4500,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Pecho",
    precio: 4000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Espalda",
    precio: 6000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Brazos",
    precio: 5000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "1/2 Brazo",
    precio: 3000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Piernas",
    precio: 6000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "1/2 Pierna",
    precio: 3500,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Gluteos",
    precio: 4500,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Tira de cola",
    precio: 3000,
    aclaraciones: "",
  },
  {
    categoria: "Depilación Definitiva Hombres",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Cavado",
    precio: 4500,
    aclaraciones: "",
  },
];

export const Uñas = [
  {
    categoria: "Uñas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Semi con nivelación",
    precio: 11000,
    aclaraciones: "",
  },
  {
    categoria: "Uñas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Capping Número 1",
    precio: 13000,
    aclaraciones: "",
  },
  {
    categoria: "Uñas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Capping Número 2",
    precio: 13500,
    aclaraciones: "",
  },
  {
    categoria: "Uñas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Capping Número 3",
    precio: 14000,
    aclaraciones: "",
  },
  {
    categoria: "Uñas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Esculpidas Número 1",
    precio: 13900,
    aclaraciones: "",
  },
  {
    categoria: "Uñas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Esculpidas Número 2",
    precio: 14500,
    aclaraciones: "",
  },
  {
    categoria: "Uñas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Esculpidas Número 3",
    precio: 15500,
    aclaraciones: "",
  },
  {
    categoria: "Uñas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Esculpidas Número 4",
    precio: 17500,
	aclaraciones: "",
  },
];

export const Adicionales = [
  {
    categoria: "Uñas. Encapsulados",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Encapsulados C/U",
    precio: 400,
    aclaraciones: "",
  },
  {
    categoria: "Uñas. Encapsulados",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Baby Boomer C/U",
    precio: 400,
    aclaraciones: "",
  },
  {
    categoria: "Uñas. Encapsulados",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Baby Glam C/U",
    precio: 500,
    aclaraciones: "",
  },
  {
    categoria: "Uñas. Encapsulados",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Full encapsulados, bayb, etc. 10U",
    precio: 3500,
    aclaraciones: "",
    unidad: "10U",
  },
  {
    categoria: "Uñas. Nail Art",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Full Frenc/full ef polvo. 10U",
    precio: 1500,
    aclaraciones: "",
  },
  {
    categoria: "Uñas. Nail Art",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Deco simple C/U",
    precio: 200,
    aclaraciones: "",
  },
  {
    categoria: "Uñas. Nail Art",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Deco compleja C/U",
    precio: 400,
    aclaraciones: "",
  },
  {
    categoria: "Uñas. Nail Art",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Deco combinada C/U",
    precio: 600,
    aclaraciones: "",
  },
  {
    categoria: "Uñas. Retiros/Piedreria",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Retiro ajeno/local solo",
    precio: 5000,
    aclaraciones: "",
  },
  {
    categoria: "Uñas. Retiros/Piedreria",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Retiro ajeno y nuevo set",
    precio: 3500,
    aclaraciones: "",
  },
  {
    categoria: "Uñas. Retiros/Piedreria",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Retiro del local y nuevo set",
    precio: 2500,
    aclaraciones: "",
  },
  {
    categoria: "Uñas. Retiros/Piedreria",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Dijes/muñecos/full stars C/U",
    precio: 600,
    aclaraciones:
      "Todo esto es hasta largo número 3 de acrílicas/capping/semi. Pasando ese largo consultar precios.",
  },
];

export const Pestañas = [
  {
    categoria: "Pestañas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Clásicas",
    precio: 14000,
    aclaraciones: "",
  },
  {
    categoria: "Pestañas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Efecto Rimel",
    precio: 15000,
    aclaraciones: "",
  },
  {
    categoria: "Pestañas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Foxy Rimel",
    precio: 15500,
    aclaraciones: "",
  },
  {
    categoria: "Pestañas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Volumen Brasileño(2D)",
    precio: 16500,
    aclaraciones: "",
  },
  {
    categoria: "Pestañas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Volumen hawaiano (3D)",
    precio: 17000,
    aclaraciones: "",
  },
  {
    categoria: "Pestañas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Volumen Argentino (5D)",
    precio: 18000,
    aclaraciones: "",
  },
  {
    categoria: "Pestañas",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Lifting + tinte + nutrición",
    precio: 12500,
    aclaraciones: "",
  },
];

export const Cejas = [
	{
	  categoria: "Cejas",
	  imagen: "/logo/logo-beauty-studio.jpg",
	  variacion: "Perfilado",
	  precio: 5000,
	  aclaraciones: "",
	},
	{
	  categoria: "Cejas",
	  imagen: "/logo/logo-beauty-studio.jpg",
	  variacion: "Laminado",
	  precio: 8000,
	  aclaraciones: "",
	},
	{
	  categoria: "Cejas",
	  imagen: "/logo/logo-beauty-studio.jpg",
	  variacion: "Perfilado + Laminado",
	  precio: 10500,
	  aclaraciones: "Todo esto incluye diseño de cejas",
	},
  ];

export const Alisados = [
  {
    categoria: "Alisado Progresivo",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Hombros",
    precio: 14000,
    aclaraciones: "aclaracion",
  },
  {
    categoria: "Alisado Progresivo",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Axilas",
    precio: 16000,
    aclaraciones: "",
  },
  {
    categoria: "Alisado Progresivo",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Medio",
    precio: 18500,
    aclaraciones: "",
  },
  {
    categoria: "Alisado Progresivo",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Cintura",
    precio: 20000,
    aclaraciones: "",
  },
];



export const Masajes = [
  {
    categoria: "Masajes",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Relajante. SHIT~SU/TAILANDES",
    precio: 16000,
    aclaraciones: "Son movimientos leves para que el cuerpo libere aire, los huesos suenen y genere relajación",
  },
  {
    categoria: "Masajes",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Relajante. Integral",
    precio: 12000,
    aclaraciones: "Masaje terapéutico, de cuerpo completo",
  },
  {
    categoria: "Masajes",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Relajante. Reflexología",
    precio: 10000,
    aclaraciones: "Masaje terapéutico, Se realiza en manos, pies o rostros.",
  },
  {
    categoria: "Masajes",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Localizados. Descontracturante",
    precio: 15000,
    aclaraciones: "Se basa en realizar presiones en los musculos para soltar las contracturas",
  },
  {
    categoria: "Masajes",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Localizados. Drenaje Linfatico",
    precio: 17000,
    aclaraciones: "Se basa en la expulsión de líquido que se almacena en el cuerpo, se presiona en los ganglios localizados",
  },
  {
    categoria: "Masajes",
    imagen: "/logo/logo-beauty-studio.jpg",
    variacion: "Localizados. Estético Reductor",
    precio: 16000,
    aclaraciones: "Se basa en reducir el tejido adiposo (la grasa) de piernas, glúteos, brazos y abdomen con vendas frías, también se utilizan distintas cremas y geles",
  },
];
